### ISSUE TITLE
needs a better security argument

### ISSUE THREAD

**Issue by sftcd** [sftcd/wkesni#18]
Part of @martinthomson's [review](https://mailarchive.ietf.org/arch/msg/tls/fOMXBXX62UmqZeR9wfs-qwkX9sU/)

> It might be the case that the design is fundamentally sound, but it isn't clear
> to me that this is true.

We can try add text to the security considerations
that argues that the design meets some security goal(s) and we can
discuss that text as we go forward.

**Comment by sftcd** [comment]
I took a not very good stab at this in #24 - needs work though...

**Comment by bemasc** [comment]
I think the trickiest thing about this is the cyclic interaction between WebPKI and DNS.  For example, if the origin's certificates are issued via ACME with an HTTP-01 challenge, and the ACME client respects HTTPS records, then an attacker who transiently compromises the secure origin could insert HTTPS records that point to its own servers, receive the subsequent ACME challenge, answer it, and become the validated holder of this and subsequent certificates.  (This is a form of "transient to persistent attack upgrade".)

I doubt any ACME servers support HTTPS records today, but the standard doesn't exactly forbid it.  (The standard [does require servers to use insecure HTTP](https://datatracker.ietf.org/doc/html/rfc8555#section-8.3:~:text=the%20challenge%20must%0A%20%20%20be%20completed%20over%20HTTP%2C%20not%20HTTPS), but Let's Encrypt [bends this rule to implement insecure "https://"](https://letsencrypt.org/docs/challenge-types/#:~:text=When%20redirected%20to%20an%20HTTPS%20URL%2C%20it%20does%20not%20validate%20certificates).)

As long as we aren't updating the A/AAAA records, this can be resolved by emphasizing that ACME servers are required to use only the A/AAAA records, since HTTPS records do not apply to insecure HTTP, by definition.

**Comment by sftcd** [comment]
I just pushed some text about that ACME issue to #24.

**Comment by richsalz** [comment]
Merged in #24, with Ben's suggestions and others.  Closing this.
